name: appmetrica_push_plugin_example
description: Demonstrates how to use the AppMetrica Push Flutter Plugin.

publish_to: 'none'

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter

  appmetrica_push_plugin:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
