// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class AMPFPermissionOptions;

@interface AMPFPermissionOptions : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithAlert:(NSNumber *)alert
    badge:(NSNumber *)badge
    sound:(NSNumber *)sound;
@property(nonatomic, strong) NSNumber * alert;
@property(nonatomic, strong) NSNumber * badge;
@property(nonatomic, strong) NSNumber * sound;
@end

/// The codec used by AMPFAppMetricaPushPigeon.
NSObject<FlutterMessageCodec> *AMPFAppMetricaPushPigeonGetCodec(void);

@protocol AMPFAppMetricaPushPigeon
- (void)activateWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)saveAppMetricaConfigConfig:(NSString *)config error:(FlutterError *_Nullable *_Nonnull)error;
- (void)getTokensWithCompletion:(void (^)(NSDictionary<NSString *, NSString *> *_Nullable, FlutterError *_Nullable))completion;
- (void)requestPermissionOptions:(AMPFPermissionOptions *)options error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void AMPFAppMetricaPushPigeonSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AMPFAppMetricaPushPigeon> *_Nullable api);

/// The codec used by AMPFTokenUpdateApi.
NSObject<FlutterMessageCodec> *AMPFTokenUpdateApiGetCodec(void);

@interface AMPFTokenUpdateApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)onTokenUpdatedNewTokens:(NSDictionary<NSString *, NSString *> *)newTokens completion:(void (^)(FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
