group "io.appmetrica.analytics.push.flutter"
version "2.5.0"

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:8.2.0"
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: "com.android.library"

android {
    if (project.android.hasProperty("namespace")) {
        namespace = "io.appmetrica.analytics.push.flutter"
    }
    buildToolsVersion "35.0.0"
    compileSdkVersion 35

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 35

        proguardFiles("proguard/proguard-rules.pro")
        consumerProguardFiles("proguard/consumer-rules.pro")
    }
}

dependencies {
    implementation("io.appmetrica.analytics:push:4.1.1")
    implementation("io.appmetrica.analytics:push-plugin-adapter:4.1.1")

    implementation("io.appmetrica.analytics:push-provider-api:4.1.1")
    implementation("io.appmetrica.analytics:push-provider-firebase:4.1.1")
}
