// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class AMPFPermissionOptions;
@class AMPFAppMetricaPushInfoPigeon;

@interface AMPFPermissionOptions : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithAlert:(NSNumber *)alert
    badge:(NSNumber *)badge
    sound:(NSNumber *)sound;
@property(nonatomic, strong) NSNumber * alert;
@property(nonatomic, strong) NSNumber * badge;
@property(nonatomic, strong) NSNumber * sound;
@end

@interface AMPFAppMetricaPushInfoPigeon : NSObject
+ (instancetype)makeWithPayload:(nullable NSString *)payload;
@property(nonatomic, copy, nullable) NSString * payload;
@end

/// The codec used by AMPFAppMetricaPushPigeon.
NSObject<FlutterMessageCodec> *AMPFAppMetricaPushPigeonGetCodec(void);

@protocol AMPFAppMetricaPushPigeon
- (void)activateWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)activateWithProvidersProviders:(NSArray<NSString *> *)providers error:(FlutterError *_Nullable *_Nonnull)error;
- (void)enableLoggerWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)getTokensWithCompletion:(void (^)(NSDictionary<NSString *, NSString *> *_Nullable, FlutterError *_Nullable))completion;
- (void)getLaunchPushInfoWithCompletion:(void (^)(AMPFAppMetricaPushInfoPigeon *_Nullable, FlutterError *_Nullable))completion;
- (void)requestPermissionOptions:(AMPFPermissionOptions *)options error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void AMPFAppMetricaPushPigeonSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AMPFAppMetricaPushPigeon> *_Nullable api);

/// The codec used by AMPFTokenUpdateApi.
NSObject<FlutterMessageCodec> *AMPFTokenUpdateApiGetCodec(void);

@interface AMPFTokenUpdateApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)onTokenUpdatedNewTokens:(NSDictionary<NSString *, NSString *> *)newTokens completion:(void (^)(FlutterError *_Nullable))completion;
@end

/// The codec used by AMPFPushReceiverApi.
NSObject<FlutterMessageCodec> *AMPFPushReceiverApiGetCodec(void);

@interface AMPFPushReceiverApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)onPushReceivedPushInfoPigeon:(AMPFAppMetricaPushInfoPigeon *)pushInfoPigeon completion:(void (^)(FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
